[package]
name = "caches"
version = "0.1.0"
authors = ["korecekm <martin.korecek.100@seznam.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rand = "0.7.3"
criterion = "0.3"
